### PR TITLE
Update html

### PR DESCRIPTION
**Pull request by danieljwilson**
Ran 

`$ docker run -v $PWD:/data expfactory/survey-generator start`

In order to regenerate `.html` file...

### CODE REVIEW

**Comment by vsoch** [comment]
There we go! :partying_face: Did you test locally to double check?

**Comment by danieljwilson** [comment]
Yes! It was working locally 👍

**Comment by vsoch** [comment]
One review item - I don't think we want to delete the survey.tsv, without it we can never update or reproduce the content.

**Comment by danieljwilson** [comment]
Hm, I don't think that it is deleted? [Link](https://github.com/danieljwilson/rosenberg-self-esteem-survey)

image

**Comment by vsoch** [comment]
Weird, the PR indicates it's an empty file - 

image

**Comment by vsoch** [comment]
I was looking at this commit: https://github.com/expfactory-experiments/rosenberg-self-esteem-survey/pull/2/commits/9373507caaa57d6042a562a852326056d623e6b1

**Comment by vsoch** [comment]
Maybe it's a bug in their render, I indeed see the file. let's try squash and merge, and please open a follow up PR if the file is mysteriously gone!

**Comment by vsoch** [comment]
Nope looks okay! How weird. Thanks for the fixup!

https://github.com/expfactory-experiments/rosenberg-self-esteem-survey/blob/main/survey.tsv

**Comment by danieljwilson** [comment]
Okay, great!

**Pull request merged**
